### ISSUE TITLE
Chinese and Japanese characters are omitted

### ISSUE THREAD

**Issue by john-walks-slow** [rcsaquino/obsidian-auto-filename#2]
Hi! This is a very useful plugin. However, I am finding that Chinese and Japanese characters are omitted from the generated file name.
For example, foo中文テストbar will be named as foobar.

**Comment by rcsaquino** [comment]
I agree with this. However, I'm not familiar with characters that are safe to use as a filename for other languages. [I'm keeping a list here](https://github.com/rcsaquino/obsidian-auto-filename/blob/a45564ab6ceab88c304bd220290fdf4351abc947/src/main.ts#L101). It's also hard for me to manually test all other languages myself. If someone is more familiar with windows, linux, and mac naming rules, I'd appreciate the help.
