### ISSUE TITLE
Support for a command to rename current note

### ISSUE THREAD

**Issue by davidrips** [rcsaquino/obsidian-auto-filename#4]
This plugin was just what I've been looking for. Is there any way to expose a command to rename the currently opened note? Most of my notes aren't in folders. Would be great if one could select multiple notes and run that command as well. Just some thoughts!

**Comment by rcsaquino** [comment]
What do you mean not in folders? You mean they're in the root of your vault? If so you could add `/` (forward slash) in the included folders list in the settings. This will rename all MD files in the root of your vault.

**Comment by davidrips** [comment]
Thanks for the reply! They are in the root, but since I'm just starting a new vault I don't have to think about having all my files automatically renamed, though there is of course the alternative situation in which someone does want all their files, in a folder or otherwise. I realize that the usecase I'm actually thinking about is that sometimes I want to title files manually, rather than having them be titled after the first line. But if I try to rename a file, and then edit it, it gets renamed again, as you said. I see why this is useful, if there's a way to persist a manually renamed title.

**Comment by rcsaquino** [comment]
I see. For now, the only way to do this is with folders since the renaming is done automatically on specified folders. I might add the option to disable automatic renaming and make it manual instead in the future if there's enough demands for it :)

**Comment by davidrips** [comment]
Sounds good! Thanks again for a great plugin!
