### ISSUE TITLE
Add option to enable automatic filenames in nested folders

### ISSUE THREAD

**Issue by kitschpatrol** [rcsaquino/obsidian-auto-filename#8]
Thanks for this plugin, it works great!

It would be really handy to be able to enable it on an entire sub-tree of folders, maybe with a glob pattern or a "recursive" flag in the settings.

**Comment by rcsaquino** [comment]
I saw your pull request and appreciate you helping out on this plugin. However, I try to keep dependencies to only important ones. In previous versions, there used to be an "Include subfolders" toggle.  It seems to be a good way to avoid pulling in dependencies and keep the plugin fast and lightweight. I'll have to think about just adding it back in or considering your pull request despite the additional dependecy.

**Comment by kitschpatrol** [comment]
Hi, thanks for responding.

Agree about dependencies, though glob matching is one of those things that seems trivial, but is tricky to get right, so there's some advantage to using a proven implementation. (I'm actually surprised there isn't a glob library exposed through Obsidian's plugin API...)

But that said, I threw in the glob approach because I didn't want to mess with your settings UI, and I hadn't seen the previous version with a  subfolders toggle. It's great if that could be brought back, and it's probably more usable for most Obsidian users than glob patterns.

**Comment by kitschpatrol** [comment]
I'll just user my fork, thanks.
